# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Smoothies' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Smoothies
  pod 'GoogleSignIn'

  target 'SmoothiesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmoothiesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
